### ISSUE TITLE
ag-grid.css is not exported from the @skyux/ag-grid package.json

### ISSUE THREAD

**Issue by Stonepaw** [blackbaud/skyux#1831]
**Describe the bug**

The instructions for [sky-ag-grid](https://developer.blackbaud.com/skyux/components/data-grid?docs-active-tab=development) include that the css should be added to the styles array of the angular app. This results in a compilation error that the css is not exported from the `@skyux/ag-grid` package:

```
Error: Package path ./css/sky-ag-grid.css is not exported from package <projectdir>/node_modules/@skyux/ag-grid (see exports field in <projectdir>/node_modules/@skyux/ag-grid/package.json)
```

Note that this is the alternative method I tried since the `sky-ag-grid.css` is not able to included with scss `@use` due to invalid css.

**Steps to reproduce the behavior**

1. Include the sky-ag-grid.css as indicated in the instructions into the angular project.json styles array
2. Compile the app
3. See error

**Expected behavior**

The documented method of including sky-ag-grid.css should work.

**Additional context**
Any other details that may relate to the problem.

[AB#2719682](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2719682)

**Comment by Blackbaud-TrevorBurch** [comment]
If you import `node_modules/@skyux/ag-grid/css/sky-ag-grid.css` it should work. We will work on a fix for the documentation.

**Comment by Blackbaud-TrevorBurch** [comment]
This has been fixed in the docs
