### ISSUE TITLE
SkyUX Documentation Typos.

### ISSUE THREAD

**Issue by ZaneGeiser** [blackbaud/skyux#1913]
Hi There,

My name is Zane and I'm new to the RedArc Engineering team.

I'm implementing some apps for Raiser Edge NXT and using skyux, interested in possibly contributing to skyux in the future. For now, I wanted to call out a few errors or things needing updating in the skyux documentation.

1. [Developer Setup page](https://developer.blackbaud.com/skyux/learn/develop/get-started#developer-setup)
    - Angular Version required for skyux 9.X.X is now Angular16.
    - When Installing the @skyux/packages, the angular.json styles have changed to
     ```
    "styles": ["@skyux/theme/css/sky.css", "@skyux/theme/css/themes/modern/styles.css"]
    ```
2. [Enable Modern Theme](https://developer.blackbaud.com/skyux/learn/visual-theme/enable-modern#theming-for-standalone-SPAs)
    - Typo in the SkyThemeSettings where `SkyThemeMode.presents.light` should be `SkyThemeMode.presets.light`

That is all for now. Please let me know if there is a better place to raise these types of documentation revisions in the future.

Cheers,
Zane

[AB#2767270](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2767270)

**Comment by Blackbaud-SteveBrush** [comment]
@ZaneGeiser Thanks for filing an issue! We'll get these documentation issues addressed right away. Please continue to file bugs or ask questions, here, thanks!

**Comment by Blackbaud-SteveBrush** [comment]
Changes have been made. Thanks again.
