### ISSUE TITLE
(ag-grid) Enable/disable row selector on a per-row basis

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [blackbaud/skyux#2269]
Currently the row selector cell renderer does not support disabling a checkbox based on a row's data. For example, if a payment is specified as "Do not print" then I want to disable the checkbox for that row when a user goes to generate a batch of payment receipts.

My proposed solution is to add a cellRendererParam property that takes a function with the cell's `params` passed in and returns true or false if the checkbox should be disabled or enabled (my thought is that it is called "shouldDisable", hence the boolean mapping)

This would also alleviate other hand-rolled cell renderers that require this functionality

[AB#2909596](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2909596)

**Comment by johnhwhite** [comment]
This was addressed in #2348. The row selector now recognizes whether a row is selectable and enables/disables the checkbox.
