### ISSUE TITLE
Ag-grid with sticky settings does not maintain sorting values

### ISSUE THREAD

**Issue by blackbaud-jeremymorgan** [blackbaud/skyux#2539]
**Describe the bug**
When using ag-grid, data manager, and sticky settings, the sorting preference isn't kept between page loads.

**Steps to reproduce the behavior**

1. Go to a grid with sorting and sticky settings enabled
2. Click on a header to sort the columns
3. Reload the page via navigation or refresh
4. The header will be marked as sorted, but the rows will not be sorted

**Expected behavior**
Sorting persists between page loads

**Screenshots**
Before refresh
![Screenshot 2024-07-23 at 11 11 06 AM](https://github.com/user-attachments/assets/63ab09d3-2c11-4333-9279-943800f7f579)

After refresh
![Screenshot 2024-07-23 at 11 12 24 AM](https://github.com/user-attachments/assets/8041a4f8-260d-4d3e-960c-1b0c60aa699c)

**Desktop details:**

- OS: MacOS
- Browser: Chrome
- Browser version: 126

**Additional context**
[In SkyAgGridDataManagerAdapterDirective](https://github.com/blackbaud/skyux/blob/b3841783f3d430b2df78c69a11257ad1b3c746c4/libs/components/ag-grid/src/lib/modules/ag-grid/ag-grid-data-manager-adapter.directive.ts#L231) there is a check for `aGridColumnState.sortIndex === 0` - during a normal sorting operation this works, but on page load with sticky settings this value is `null` and so triggers an update to the sticky settings, removing the active sort. `aGridColumnState.sort` at the same time has the appropriate `asc` or `desc` string value.

**Comment by johnhwhite** [comment]
This issue was resolved in #2820.
