### ISSUE TITLE
coerceBooleanProperty can reference the Angular CDK

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux#581]
Hi friends!

Just noticed today that the [CDK](https://material.angular.io/cdk/coercion/api) has their own `coerceBooleanProperty` function that can replace the custom one we made:

https://github.com/blackbaud/skyux/blob/a84cda20832fa1914b8e9bf52ca60c39d27b0ee2/libs/components/forms/src/lib/modules/shared/forms-utility.ts#L9

Less code to manage. Winner winner - chicken dinner. 💥

**Comment by Blackbaud-TrevorBurch** [comment]
Closing as we have made an internal note of this and have implemented in a couple places already. Thanks @Blackbaud-AlexKingman!
